import {
  Baby,
  BookOpen,
  Camera,
  Car,
  Clapperboard,
  Disc3,
  Dumbbell,
  Factory,
  Gamepad2,
  Gem,
  Guitar,
  HardHat,
  HeartPulse,
  Laptop,
  Palette,
  PartyPopper,
  PawPrint,
  Pill,
  Puzzle,
  Refrigerator,
  Shirt,
  Smartphone,
  Sofa,
  Sparkles,
  Tractor,
  Tv,
  UtensilsCrossed,
  Watch,
  Wrench,
  type LucideIcon,
  Shapes,
} from "lucide-react"

const ICONS: Record<string, LucideIcon> = {
  "eletronicos": Tv,
  "informatica": Laptop,
  "celulares": Smartphone,
  "casa": Sofa,
  "eletrodomesticos": Refrigerator,
  "moda": Shirt,
  "beleza": Sparkles,
  "saude": HeartPulse,
  "esporte": Dumbbell,
  "suplementos": Pill,
  "dj": Disc3,
  "games": Gamepad2,
  "bebes": Baby,
  "brinquedos": Puzzle,
  "acessorios-veiculos": Car,
  "agro": Tractor,
  "alimentos-bebidas": UtensilsCrossed,
  "animais": PawPrint,
  "antiguidades": Gem,
  "arte-papelaria": Palette,
  "cameras": Camera,
  "construcao": HardHat,
  "ferramentas": Wrench,
  "festas": PartyPopper,
  "industria": Factory,
  "instrumentos": Guitar,
  "joias-relogios": Watch,
  "livros": BookOpen,
  "musica-filmes": Clapperboard,
}

export const categoryIcon = (slug: string): LucideIcon => ICONS[slug] ?? Shapes
